import type { Metadata } from "next";
import "../../styles/globals.css";
import UserNavbar from "@/components/userComponents/ui/UserNavbar/UserNavbar";
import { Footer } from "@/components/baseComponents/ui/Footer/Footer";

export const metadata: Metadata = {
  title: "Cure Track",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <UserNavbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
